# Generated by Django 4.1.7 on 2023-08-19 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0006_vendor_credits_bills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor_credits_bills_items_bills',
            name='company',
        ),
        migrations.RemoveField(
            model_name='vendor_credits_bills_items_bills',
            name='recur_bills',
        ),
        migrations.RemoveField(
            model_name='vendor_credits_bills_items_bills',
            name='user',
        ),
        migrations.DeleteModel(
            name='Vendor_Credits_Bills',
        ),
        migrations.DeleteModel(
            name='Vendor_Credits_Bills_items_bills',
        ),
    ]
