# Generated by Django 4.1.7 on 2023-09-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0009_credits_mail_table_credits_doc_upload_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor_credits_bills',
            old_name='customer_name',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='vendor_credits_bills',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='vendor_credits_bills',
            name='payment_terms',
        ),
        migrations.RemoveField(
            model_name='vendor_credits_bills',
            name='shipping_charge',
        ),
        migrations.RemoveField(
            model_name='vendor_credits_bills_items_bills',
            name='account',
        ),
        migrations.AddField(
            model_name='vendor_credits_bills',
            name='gst_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
